FROM cp.icr.io/cp/manage/extension-acm@sha256:41f2630dce7f7085f3e947f7bc9e88a683ad48529f74cbef40fe1c0d3040fab9 AS ACM
FROM cp.icr.io/cp/manage/extension-serviceprovider@sha256:0208411d76cf669263a08c90f2009457e75ba52a8bf5ace7eac430972ccd91e9 AS SERVICEPROVIDER
FROM cp.icr.io/cp/manage/extension-hse@sha256:16eaba8ea70a147734efd016438a5fb3fd8d54f741b38c092dc24621a72208fe AS HSE
FROM cp.icr.io/cp/manage/extension-transportation@sha256:d170f648b2b90c8b8213bb0ceaefac10a74e92b77e8609267e5a952a30173e8d AS TRANSPORTATION
FROM cp.icr.io/cp/manage/extension-aviation@sha256:0c274c3753e469f201e6b08969cd04bb79896ae58a9fd73fe223f5d63b4d5f91 AS AVIATION
FROM cp.icr.io/cp/manage/extension-health@sha256:b948a96e7be3bf814c0231d421a3fd4307caa2ec3221a6f56bde192137412682 AS HEALTH
FROM cp.icr.io/cp/manage/manageadmin@sha256:61a976e7012bab63c29b43a0e73a816583580e82e0b0f959463e78d8347a15c7 AS BASE


WORKDIR /opt/IBM/SMP/maximo


######## HEALTH ########
# COPY --chown=1000:0 --from=HEALTH /extension.zip /opt/IBM/SMP/maximo/
# RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\
#  unzip -o tools/maximo/en/assethealth/package.zip -d tools/maximo
######## END OF HEALTH ########

######## HSE ########
COPY --chown=1000:0 --from=HSE /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip
######## END OF HEALTH ########

######## ICD ########
#COPY --chown=1000:0 --from=ICD /extension.zip /opt/IBM/SMP/maximo/
#RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\
#  unzip -o tools/maximo/en/icd/package.zip -d tools/maximo
######## END OF ICD ########

######## SERVICEPROVIDER ########
COPY --chown=1000:0 --from=SERVICEPROVIDER /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip
######## END OF SERVICEPROVIDER ########

######## STRATEGIZE ########
#COPY --chown=1000:0 --from=STRATEGIZE /extension.zip /opt/IBM/SMP/maximo/
#RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\ 
#  unzip -o tools/maximo/en/strategize/package.zip -d tools/maximo
######## END OF STRATEGIZE ########

######## NUCLEAR ########
#COPY --chown=1000:0 --from=NUCLEAR /extension.zip /opt/IBM/SMP/maximo/
#RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\ 
#  unzip -o tools/maximo/en/nuclear/package.zip -d tools/maximo
######## END OF NUCLEAR ########

######## TRANSPORTATION ########
COPY --chown=1000:0 --from=TRANSPORTATION /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip 
######## END OF TRANSPORTATION ########

######## ACM ########
COPY --chown=1000:0 --from=ACM /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip 
######## END OF ACM ########

######## AVIATION ########
COPY --chown=1000:0 --from=AVIATION /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip &&\ 
  unzip -o tools/maximo/en/mama/package.zip -d tools/maximo
######## END OF AVIATION ########

WORKDIR /opt/IBM/SMP/maximo
RUN for i in $(ls -1 lang/*.zip); do unzip $i;done

WORKDIR /opt/IBM/SMP/maximo/tools/maximo

RUN \
  mkdir -p /opt/IBM/SMP/maximo/applications/maximo/businessobjects/classes/psdi/app/signature/apps &&\
  mkdir -p /opt/IBM/SMP/maximo/tools/maximo/log &&\
  ./pkginstall.sh && ./updatedblitepreprocessor.sh -disconnected &&\
  find /opt/IBM/SMP/maximo/applications -type d -exec chmod 777 {} + &&\
  chmod ugo+rw -R /opt/IBM/SMP/maximo/applications &&\
  find /opt/IBM/SMP/maximo/tools/maximo -type d -exec chmod 777 {} + &&\
  chmod ugo+rw -R /opt/IBM/SMP/maximo/tools/maximo &&\
  chmod 777 /opt/IBM/SMP/maximo/tools/maximo/log &&\
  find /opt/IBM/SMP/maximo/tools/maximo/en -type f -name postupdatedb.sh -exec chmod -v 777 {} + &&\
  find /opt/IBM/SMP/maximo/tools/maximo/en -type f -name postpreprocessor.sh -exec chmod -v 777 {} +

# RUN find /opt/IBM/SMP/maximo/tools/maximo/en -type f -name postpreprocessor.sh -exec {} \;

WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-servers/maximo-all/maximo-all-server
RUN mv server.xml server-oidc.xml
RUN mv server-dev.xml server.xml

## Replace web.xml for maximo-all maximo-x
#WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximo-x/webmodule/WEB-INF/
#RUN mv web.xml web-oidc.xml
#RUN mv web-guest.xml  web-guest-oidc.xml
#RUN mv web-dev.xml  web.xml
#RUN mv web-guest-dev.xml  web-guest.xml

## Replace web.xml for maximo-all maximouiweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/
RUN mv /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web.xml /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web-oidc.xml
RUN mv /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web-dev.xml /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web.xml
# set session timeout to 720 mins for maximo ui web
RUN sed -i 's/<session-timeout>30</<session-timeout>720</g' /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web.xml


## Replace web.xml for maximo-all maxrestweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maxrestweb/webmodule/WEB-INF/
RUN mv web.xml web-oidc.xml
RUN mv web-dev.xml  web.xml


## Replace web.xml for maximo-all mboweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/mboweb/webmodule/WEB-INF/
RUN mv web.xml web-oidc.xml
RUN mv web-dev.xml  web.xml


## Replace web.xml for maximo-all meaweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/meaweb/webmodule/WEB-INF/
RUN mv web.xml web-oidc.xml
RUN mv web-dev.xml  web.xml

#WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-x/webmodule/WEB-INF/
#RUN mv web.xml web-oidc.xml
#RUN mv web-guest.xml  web-guest-oidc.xml
#RUN mv web-dev.xml  web.xml
#RUN mv web-guest-dev.xml  web-guest.xml

WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default
RUN ./maximo-all.sh

RUN echo "-Xmx8192m" >> /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server/jvm.options
RUN echo "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777" >> /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server/jvm.options

FROM websphere-liberty:25.0.0.11-full-java17-openj9
# FROM cp.icr.io/cp/manage/ubi-wlp-manage@sha256:cf48c0ecbdc53754f4e9bfc13dc36eae1ea78670429113d7fd564cdb2c9cc20d

COPY --chown=1001:0 --from=BASE /opt/IBM /opt/IBM/
COPY --chown=1001:0 --from=BASE /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server /config/
COPY --chown=1001:0 update-maximoproperties.sh /opt/IBM
COPY --chown=1001:0 updatedb-needed.sh /opt/IBM
COPY --chown=1001:0 docker-server.sh /opt/ibm/helpers/runtime/
COPY --chown=1001:0 server-custom.xml /config

RUN rm -rf /opt/IBM/SMP/maximo/tools/java

COPY --chown=1001:0 --from=BASE /opt/ibm/java /opt/IBM/SMP/maximo/tools/java
RUN rm -f /opt/IBM/SMP/maximo/tools/java/jre
RUN ln -s /opt/IBM/SMP/maximo/tools/java /opt/IBM/SMP/maximo/tools/java/jre
# COPY /opt/IBM/SMP/maximo/tools/java /opt/IBM/SMP/maximo/tools/java/jre

RUN chmod a+x /opt/IBM/update-maximoproperties.sh
# Fix out of memory issue during maximo boot process

RUN configure.sh


# Unzip maximo-all.ear and relevant wars and jars to allow modification of maximo.properties and web.xml files
RUN \
  mv /config/apps/maximo-all.ear /config/apps/maximo-all.ear.zip &&\
  mkdir /config/apps/maximo-all.ear
  
WORKDIR /config/apps/maximo-all.ear 
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear.zip
RUN mv /config/apps/maximo-all.ear/maximouiweb.war /config/apps/maximo-all.ear/maximouiweb.war.zip
RUN mv /config/apps/maximo-all.ear/maxrestweb.war /config/apps/maximo-all.ear/maxrestweb.war.zip
RUN mv /config/apps/maximo-all.ear/mboweb.war /config/apps/maximo-all.ear/mboweb.war.zip
RUN mv /config/apps/maximo-all.ear/meaweb.war /config/apps/maximo-all.ear/meaweb.war.zip
RUN mv /config/apps/maximo-all.ear/properties.jar /config/apps/maximo-all.ear/properties.jar.zip
RUN mv /config/apps/maximo-all.ear/mboejb.jar /config/apps/maximo-all.ear/mboejb.jar.zip
RUN mv /config/apps/maximo-all.ear/businessobjects.jar /config/apps/maximo-all.ear/businessobjects.jar.zip

RUN \
mkdir /config/apps/maximo-all.ear/maximouiweb.war &&\
mkdir /config/apps/maximo-all.ear/maxrestweb.war &&\
mkdir /config/apps/maximo-all.ear/mboweb.war &&\
mkdir /config/apps/maximo-all.ear/meaweb.war &&\
mkdir /config/apps/maximo-all.ear/properties.jar &&\
mkdir /config/apps/maximo-all.ear/mboejb.jar &&\
mkdir /config/apps/maximo-all.ear/businessobjects.jar

WORKDIR /config/apps/maximo-all.ear/maximouiweb.war
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/maximouiweb.war.zip

WORKDIR /config/apps/maximo-all.ear/maxrestweb.war
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/maxrestweb.war.zip
WORKDIR /config/apps/maximo-all.ear/mboweb.war
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/mboweb.war.zip
WORKDIR /config/apps/maximo-all.ear/meaweb.war
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/meaweb.war.zip
WORKDIR /config/apps/maximo-all.ear/properties.jar
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/properties.jar.zip
WORKDIR /config/apps/maximo-all.ear/mboejb.jar
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/mboejb.jar.zip
WORKDIR /config/apps/maximo-all.ear/businessobjects.jar
RUN /opt/IBM/SMP/maximo/tools/java/bin/jar -vxf /config/apps/maximo-all.ear/businessobjects.jar.zip

RUN\
  rm /config/apps/maximo-all.ear.zip &&\
  rm /config/apps/maximo-all.ear/maximouiweb.war.zip &&\
  rm /config/apps/maximo-all.ear/maxrestweb.war.zip &&\
  rm /config/apps/maximo-all.ear/mboweb.war.zip &&\
  rm /config/apps/maximo-all.ear/meaweb.war.zip &&\
  rm /config/apps/maximo-all.ear/properties.jar.zip &&\
  rm /config/apps/maximo-all.ear/mboejb.jar.zip &&\
  rm /config/apps/maximo-all.ear/businessobjects.jar.zip

WORKDIR /config
#RUN sed -i -e "s/\(mxe.db.schemaowner\)=\(.*\)/\1=$MXE_DB_SCHEMAOWNER/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.url\)=\(.*\)/\1=$MXE_DB_URL/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.driver\)=\(.*\)/\1=$MXE_DB_DRIVER/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.user\)=\(.*\)/\1=$MXE_DB_USER/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.password\)=\(.*\)/\1=$MXE_DB_PASSWORD/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_OLD_CRYPTO_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_CRYPTO_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_OLD_CRYPTOX_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_CRYPTOX_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties


ENV MXE_DB_SCHEMAOWNER=
ENV MXE_DB_URL=
ENV MXE_DB_DRIVER=
ENV MXE_SECURITY_OLD_CRYPTO_KEY=
ENV MXE_SECURITY_CRYPTO_KEY=
ENV MXE_SECURITY_OLD_CRYPTOX_KEY=
ENV MXE_SECURITY_CRYPTOX_KEY=
ENV MXE_DB_USER=maximo
ENV MXE_DB_PASSWORD=maximo
ENV MAXIMO_DATAFILE=maxdemo

