FROM cp.icr.io/cp/manage/extension-acm@sha256:c4a36022d8b6508dcd49908d229f14dd34552ad2d16e09a612b13aff34e28cfc AS ACM
FROM cp.icr.io/cp/manage/extension-serviceprovider@sha256:055e9d26797d33119aef56b0e5314e3821c3ce897512083620e89b65a68c1995 AS SERVICEPROVIDER
FROM cp.icr.io/cp/manage/extension-hse@sha256:7bf8b5b1f404655c7dd1d9a8e9ef35af2b30edd4a94fba667b10662cc7870932 AS HSE
FROM cp.icr.io/cp/manage/extension-transportation@sha256:d44ce0a1cde2e7005e9cd41e043e56a9a1e5bb17255d6e097ad90545b0b50738 AS TRANSPORTATION
FROM cp.icr.io/cp/manage/extension-aviation@sha256:03ab387e97ca947433277fd001fb662578b03eb49af5c2445e562107854919c5 AS AVIATION
FROM cp.icr.io/cp/manage/extension-health@sha256:cdd99dff0ebc6d5282c052c1d1fd9b4e1cce11ec2142b27637ee905ce390156c AS HEALTH
FROM cp.icr.io/cp/manage/manageadmin@sha256:7579dd3dc3761545e7ce6f1c4c9780b0bffaa5160b5639c55f7650a5a1842634 AS BASE


WORKDIR /opt/IBM/SMP/maximo


######## HEALTH ########
# COPY --chown=1000:0 --from=HEALTH /extension.zip /opt/IBM/SMP/maximo/
# RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\
#  unzip -o tools/maximo/en/assethealth/package.zip -d tools/maximo
######## END OF HEALTH ########

######## HSE ########
COPY --chown=1000:0 --from=HSE /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip
######## END OF HEALTH ########

######## ICD ########
#COPY --chown=1000:0 --from=ICD /extension.zip /opt/IBM/SMP/maximo/
#RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\
#  unzip -o tools/maximo/en/icd/package.zip -d tools/maximo
######## END OF ICD ########

######## SERVICEPROVIDER ########
COPY --chown=1000:0 --from=SERVICEPROVIDER /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip
######## END OF SERVICEPROVIDER ########

######## STRATEGIZE ########
#COPY --chown=1000:0 --from=STRATEGIZE /extension.zip /opt/IBM/SMP/maximo/
#RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\ 
#  unzip -o tools/maximo/en/strategize/package.zip -d tools/maximo
######## END OF STRATEGIZE ########

######## NUCLEAR ########
#COPY --chown=1000:0 --from=NUCLEAR /extension.zip /opt/IBM/SMP/maximo/
#RUN \
#  unzip -o ./extension.zip && rm ./extension.zip &&\ 
#  unzip -o tools/maximo/en/nuclear/package.zip -d tools/maximo
######## END OF NUCLEAR ########

######## TRANSPORTATION ########
COPY --chown=1000:0 --from=TRANSPORTATION /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip 
######## END OF TRANSPORTATION ########

######## ACM ########
COPY --chown=1000:0 --from=ACM /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip 
######## END OF ACM ########

######## AVIATION ########
COPY --chown=1000:0 --from=AVIATION /extension.zip /opt/IBM/SMP/maximo/
RUN \
  unzip -o ./extension.zip && rm ./extension.zip &&\ 
  unzip -o tools/maximo/en/mama/package.zip -d tools/maximo
######## END OF AVIATION ########

WORKDIR /opt/IBM/SMP/maximo
RUN for i in $(ls -1 lang/*.zip); do unzip $i;done

WORKDIR /opt/IBM/SMP/maximo/tools/maximo

RUN \
  mkdir -p /opt/IBM/SMP/maximo/applications/maximo/businessobjects/classes/psdi/app/signature/apps &&\
  mkdir -p /opt/IBM/SMP/maximo/tools/maximo/log &&\
  ./pkginstall.sh && ./updatedblitepreprocessor.sh -disconnected &&\
  find /opt/IBM/SMP/maximo/applications -type d -exec chmod 777 {} + &&\
  chmod ugo+rw -R /opt/IBM/SMP/maximo/applications &&\
  find /opt/IBM/SMP/maximo/tools/maximo -type d -exec chmod 777 {} + &&\
  chmod ugo+rw -R /opt/IBM/SMP/maximo/tools/maximo &&\
  chmod 777 /opt/IBM/SMP/maximo/tools/maximo/log &&\
  find /opt/IBM/SMP/maximo/tools/maximo/en -type f -name postupdatedb.sh -exec chmod -v 777 {} + &&\
  find /opt/IBM/SMP/maximo/tools/maximo/en -type f -name postpreprocessor.sh -exec chmod -v 777 {} +

# RUN find /opt/IBM/SMP/maximo/tools/maximo/en -type f -name postpreprocessor.sh -exec {} \;

WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-servers/maximo-all/maximo-all-server
RUN mv server.xml server-oidc.xml
RUN mv server-dev.xml server.xml

## Replace web.xml for maximo-all maximo-x
#WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximo-x/webmodule/WEB-INF/
#RUN mv web.xml web-oidc.xml
#RUN mv web-guest.xml  web-guest-oidc.xml
#RUN mv web-dev.xml  web.xml
#RUN mv web-guest-dev.xml  web-guest.xml

## Replace web.xml for maximo-all maximouiweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/
RUN mv /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web.xml /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web-oidc.xml
RUN mv /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web-dev.xml /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maximouiweb/webmodule/WEB-INF/web.xml


## Replace web.xml for maximo-all maxrestweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/maxrestweb/webmodule/WEB-INF/
RUN mv web.xml web-oidc.xml
RUN mv web-dev.xml  web.xml


## Replace web.xml for maximo-all mboweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/mboweb/webmodule/WEB-INF/
RUN mv web.xml web-oidc.xml
RUN mv web-dev.xml  web.xml


## Replace web.xml for maximo-all meaweb
WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-all/meaweb/webmodule/WEB-INF/
RUN mv web.xml web-oidc.xml
RUN mv web-dev.xml  web.xml

#WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default/config-deployment-descriptors/maximo-x/webmodule/WEB-INF/
#RUN mv web.xml web-oidc.xml
#RUN mv web-guest.xml  web-guest-oidc.xml
#RUN mv web-dev.xml  web.xml
#RUN mv web-guest-dev.xml  web-guest.xml

WORKDIR /opt/IBM/SMP/maximo/deployment/was-liberty-default
RUN ./maximo-all.sh

RUN echo "-Xmx8192m" >> /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server/jvm.options

FROM websphere-liberty:24.0.0.8-full-java8-ibmjava

COPY --chown=1001:0 --from=BASE /opt/IBM /opt/IBM/
COPY --chown=1001:0 --from=BASE /opt/IBM/SMP/maximo/deployment/was-liberty-default/deployment/maximo-all/maximo-all-server /config/
COPY --chown=1001:0 update-maximoproperties.sh /opt/IBM
COPY --chown=1001:0 updatedb-needed.sh /opt/IBM
COPY --chown=1001:0 docker-server.sh /opt/ibm/helpers/runtime/
COPY --chown=1001:0 server-custom.xml /config

RUN chmod a+x /opt/IBM/update-maximoproperties.sh
# Fix out of memory issue during maximo boot process

RUN configure.sh

#RUN sed -i -e "s/\(mxe.db.schemaowner\)=\(.*\)/\1=$MXE_DB_SCHEMAOWNER/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.url\)=\(.*\)/\1=$MXE_DB_URL/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.driver\)=\(.*\)/\1=$MXE_DB_DRIVER/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.user\)=\(.*\)/\1=$MXE_DB_USER/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i -e "s/\(mxe.db.password\)=\(.*\)/\1=$MXE_DB_PASSWORD/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_OLD_CRYPTO_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_CRYPTO_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_OLD_CRYPTOX_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties
#RUN sed -i "s/(mxe.db.schemaowner)=(.*)/$1=$MXE_SECURITY_CRYPTOX_KEY/g" /opt/IBM/SMP/maximo/applications/maximo/properties/maximo.properties


ENV MXE_DB_SCHEMAOWNER=
ENV MXE_DB_URL=
ENV MXE_DB_DRIVER=
ENV MXE_SECURITY_OLD_CRYPTO_KEY=
ENV MXE_SECURITY_CRYPTO_KEY=
ENV MXE_SECURITY_OLD_CRYPTOX_KEY=
ENV MXE_SECURITY_CRYPTOX_KEY=
ENV MXE_DB_USER=maximo
ENV MXE_DB_PASSWORD=maximo
ENV MAXIMO_DATAFILE=maxdemo

